mm-compaction-introduce-sync-light-migration-for-use-by-compaction-fix-fix
fs/nfs/write.c: In function 'nfs_migrate_page':
fs/nfs/write.c:1729: error: 'sync' undeclared (first use in this function)

Cc: Mel Gorman <mgorman@suse.de>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>