sysreq.c needs uaccess.h for get_user
Commit b1cdabb05024 ("fs: move code out of buffer.c") removed the include
of linux/buffer_head.h which was presumably implictly including uaccess.h
on sparc32.

Fixes this build error:

drivers/tty/sysrq.c: In function 'write_sysrq_trigger':
drivers/tty/sysrq.c:867:3: error: implicit declaration of function 'get_user' [-Werror=implicit-function-declaration]

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>