tile: fix compile failure on start_kernel in setup.c
Commit 293ef7b8288da79112276ddd53902aff75ce7494

    "tile: Use generic init_task"

deleted the file tile/kernel/init_task.c and moved the remaining
needed code to tile/kernel/setup.c -- but this code references
start_kernel and setup.c didn't include that, causing this fail:

arch/tile/kernel/setup.c:69:344: error: 'start_kernel' undeclared here (not in a function)

Adding the obvious include fixes it.

Cc: Thomas Gleixner <tglx@linutronix.de>
Acked-by: Chris Metcalf <cmetcalf@tilera.com>
Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>