gpio/pch: Fix build failure when selected as a module
x86_64 allmodconfig fails like this:

ERROR: "handle_edge_irq" [drivers/gpio/gpio-pch.ko] undefined!
ERROR: "irq_to_desc" [drivers/gpio/gpio-pch.ko] undefined!

This patch fixes the issue by not allowing gpio-pch.c to be built as a
module.  It can be reenabled when the core interrupt handling code
exports the missing symbols, but that change needs some review first.

Signed-off-by: Grant Likely <grant.likely@secretlab.ca>
Cc: Thomas Gleixner <tglx@linutronix.de>
Cc: "David S. Miller" <davem@davemloft.net>
Cc: Stephen Rothwell <sfr@canb.auug.org.au>