mfd/Input/ASoC: twl6040 kconfig fixes
To avoid breaking x86_64 allmodconfig build the Kconfig files need to be
changed.
Change the dependency graph of the twl6040 stack.

This commit fixes:

drivers/built-in.o: In function `twl6040_driver_init':
twl6040-core.c:(.init.text+0xb147): undefined reference to `i2c_register_driver'
drivers/built-in.o: In function `twl6040_probe':
twl6040-core.c:(.devinit.text+0x7f22): undefined reference to `regmap_init_i2c'
drivers/built-in.o: In function `twl6040_driver_exit':
twl6040-core.c:(.exit.text+0x67a): undefined reference to `i2c_del_driver'

Reported-by: Stephen Rothwell <sfr@canb.auug.org.au>
Signed-off-by: Peter Ujfalusi <peter.ujfalusi@ti.com>
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>