sh: fix several build failures from system.h fallout
commit e839ca528718e68cad32a307dc9aabf01ef3eb05

    "Disintegrate asm/system.h for SH"

created the new file asm/cache_insns.h but it didn't add
an include for all the users of it.

The failure on fpu.c (also seen below) showed up roughly
at the same time, and since the fix is trivial (include traps.h)
I did not bother to bisect to 100% confirm it was caused by
the system.h disintegration.

arch/sh/mm/flush-sh4.c:16:2: error: implicit declaration of function 'register_align' [-Werror=implicit-function-declaration]
arch/sh/mm/flush-sh4.c:23:3: error: implicit declaration of function '__ocbwb' [-Werror=implicit-function-declaration]
arch/sh/mm/flush-sh4.c:57:3: error: implicit declaration of function '__ocbp' [-Werror=implicit-function-declaration]
arch/sh/mm/flush-sh4.c:87:3: error: implicit declaration of function '__ocbi' [-Werror=implicit-function-declaration]
cc1: all warnings being treated as errors
make[2]: *** [arch/sh/mm/flush-sh4.o] Error 1
arch/sh/mm/cache-sh4.c:70:3: error: implicit declaration of function '__ocbwb' [-Werror=implicit-function-declaration]
cc1: all warnings being treated as errors
make[2]: *** [arch/sh/mm/cache-sh4.o] Error 1
arch/sh/kernel/cpu/fpu.c:81:2: error: 'TRAP_HANDLER_DECL' undeclared (first use in this function)
arch/sh/kernel/cpu/fpu.c:83:20: error: 'regs' undeclared (first use in this function)
arch/sh/kernel/cpu/fpu.c:83:19: error: called object 'fpu_state_restore' is not a function
make[3]: *** [arch/sh/kernel/cpu/fpu.o] Error 1
arch/sh/kernel/cpu/sh4/fpu.c:407:2: error: 'TRAP_HANDLER_DECL' undeclared (first use in this function)
arch/sh/kernel/cpu/sh4/fpu.c:409:20: error: 'regs' undeclared (first use in this function)
make[4]: *** [arch/sh/kernel/cpu/sh4/fpu.o] Error 1

Cc: Paul Mundt <lethal@linux-sh.org>
Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>