leds: fix build error for LP55xx Common driver
To solve undefined symbols for LED class and I2C, lp55xx-common driver should
support a module build as well.

In case of CONFIG_I2C=m, CONFIG_LEDS_LP5521/5523=m, it still has undefined
symbol problems because CONFIG_LEDS_LP55XX_COMMON can be selected as 'y'.
Moreover, I2C functions are used in both LP5521 and LP5523 drivers.
Therefore, each LP55xx driver should have an 'I2C' dependency.

make x86_64 allmodconfig failed like this:

drivers/built-in.o: In function `lp55xx_unregister_leds':
(.text+0x161dab): undefined reference to `led_classdev_unregister'

drivers/built-in.o: In function `lp55xx_init_led':
leds-lp55xx-common.c:(.text+0x161f23): undefined reference to `led_classdev_register'
leds-lp55xx-common.c:(.text+0x161f9f): undefined reference to `led_classdev_unregister'

drivers/built-in.o: In function `lp55xx_read':
(.text+0x1621b3): undefined reference to `i2c_smbus_read_byte_data'
drivers/built-in.o: In function `lp55xx_init_device':
(.text+0x1622f0): undefined reference to `i2c_smbus_write_byte_data'
drivers/built-in.o: In function `lp55xx_init_device':
(.text+0x162331): undefined reference to `i2c_smbus_write_byte_data'
drivers/built-in.o: In function `lp55xx_update_bits':
(.text+0x162492): undefined reference to `i2c_smbus_write_byte_data'
drivers/built-in.o: In function `lp55xx_write':
(.text+0x1624c5): undefined reference to `i2c_smbus_write_byte_data'

Signed-off-by: Milo(Woogyom) Kim <milo.kim@ti.com>
Signed-off-by: Bryan Wu <cooloney@gmail.com>