ARM: mach-msm: fix compile fail from system.h fallout
To fix:

  In file included from arm/boot/compressed/misc.c:28:0:
  arm/mach-msm/include/mach/uncompress.h: In function 'putc':
  arch/arm/mach-msm/include/mach/uncompress.h:48:3: error: implicit
  declaration of function 'smp_mb' [-Werror=implicit-function-declaration]

The putc does a cpu_relax which for this platform is smp_mb.

Bisect indicates the 1st failing commit as:

    commit 0195c00244dc2e9f522475868fa278c473ba7339
    "Merge tag 'split-asm_system_h-for-linus-20120328' ..."

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>