MIPS: delete bogus module.h usage in termios.h
There is no need for this.  Removing it causes a small amount
of fallout (shown below) due to a few implicit header presence
assumptions that are easily fixed.

arch/mips/include/asm/termios.h:103: error: implicit declaration of function 'access_ok'
arch/mips/include/asm/module.h:17: error: expected specifier-qualifier-list before 'Elf64_Addr'

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>