ARM: 7273/1: EXYNOS: Fix build error which was from common.c and old cpu.c
This fixes build error and wrong merge conflicts.
arch/arm/mach-exynos/common.c: In function 'exynos4_gic_irq_fix_base':
arch/arm/mach-exynos/common.c:393: error: dereferencing pointer to incomplete type
arch/arm/mach-exynos/common.c:396: error: dereferencing pointer to incomplete type

Following A and B have been created from different base and the build
error was casued in the process of merging and should be fixed in this
merge window.

A. commit db0d4db ("ARM: gic: allow GIC to support non-banked setups"),
  commit 4e44d2c ("ARM: exynos4: convert to CONFIG_MULTI_IRQ_HANDLER")
  and commit 69676c3 ("ARM: exynos4: Fix build error due to
  'gic_bank_offset' undeclared")

B. commit cc511b8 ("ARM: 7257/1: EXYNOS: introduce arch/arm/mach-exynos/
  common.[ch]") introduced common.[ch]")

Cc: Marc Zyngier <marc.zyngier@arm.com>
Cc: Axel Lin <axel.lin@gmail.com>
Signed-off-by: Kukjin Kim <kgene.kim@samsung.com>
Signed-off-by: Russell King <rmk+kernel@arm.linux.org.uk>