uprobes: using ENOSYS requires errno.h
Fixes this build propblem:

In file included from include/linux/mm_types.h:15:0,
                 from include/linux/kmemcheck.h:4,
                 from include/linux/skbuff.h:18,
                 from net/8021q/vlan_core.c:1:
include/linux/uprobes.h: In function 'register_uprobe':
include/linux/uprobes.h:148:10: error: 'ENOSYS' undeclared (first use in this function)

when CONFIG_UPROBES is not defined.

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>