security: commoncaps.c needs to include personality.h
fixes this build error on PowerPC:

security/commoncap.c: In function 'cap_bprm_set_creds':
security/commoncap.c:510:22: error: 'PER_CLEAR_ON_SETID' undeclared (first use in this function)

Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>