bug.h: Fix x86 !CONFIG_BUG build regression
Commit 2603efa31a03 ("bug.h: Fix up powerpc build regression.")
broke most x86 !CONFIG_BUG builds in -rc4:

  include/linux/cpumask.h: In function ‘cpumask_check’:
  include/linux/cpumask.h:108:2: error: implicit declaration of function ‘WARN_ON_ONCE’
  [...]

The commit mis-placed the !ASSEMBLY block, mixing it with the
CONFIG_BUG section.

Hiding an #include <kernel.h> deep inside a generic header is in
pretty bad taste anyway, it creates kconfig dependent breakages
and makes it harder to untangle header files.

Signed-off-by: Ingo Molnar <mingo@kernel.org>
Cc: Linus Torvalds <torvalds@linux-foundation.org>
Cc: Stephen Rothwell <sfr@canb.auug.org.au>
Cc: Randy Dunlap <rdunlap@xenotime.net>
Cc: Peter Zijlstra <a.p.zijlstra@chello.nl>
Cc: Paul Mundt <lethal@linux-sh.org>
Link: http://lkml.kernel.org/r/20120625094215.GA25847@gmail.com
Signed-off-by: Ingo Molnar <mingo@kernel.org>